added test command

diff --git a/.github/workflows/ci-cd-vars.yml b/.github/workflows/ci-cd-vars.yml
--- a/.github/workflows/ci-cd-vars.yml
+++ b/.github/workflows/ci-cd-vars.yml
@@ -16,7 +16,9 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Use a secret from evironment
-        run: echo "The secret is ${{ secrets.FIRST_SECRET }}"
+        run: |
+          echo "The secret is ${{ secrets.FIRST_SECRET }}"
+          test -n "$FIRST_SECRET" || (echo "Missing FIRST_SECRET" && exit 1)
 
       # - name: Use Secret
       #   env:
