update the code

diff --git a/.github/workflows/ci-cd-vars.yml b/.github/workflows/ci-cd-vars.yml
--- a/.github/workflows/ci-cd-vars.yml
+++ b/.github/workflows/ci-cd-vars.yml
@@ -18,7 +18,7 @@ jobs:
       - name: Use a secret from evironment
         run: |
           echo "The secret is ${{ secrets.FIRST_SECRET }}"
-          test -n "$FIRST_SECRET" || (echo "Missing FIRST_SECRET" && exit 1)
+          test -n "${{ secrets.FIRST_SECRET }}" || (echo "Missing FIRST_SECRET" && exit 1)
 
       # - name: Use Secret
       #   env:
